#!/usr/bin/env bash
# Stage 1 of the repo cleanup: git hygiene only. Nothing is moved, no code changes, and every file
# stays on your disk, so running services keep working. Safe to run while the pipeline is up.
#
# Run from ~/login-events:   bash tidy_repo_stage1.sh
# Then review with `git status`, and commit when you are happy.
set -euo pipefail
cd "$(dirname "$0")"
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "not a git repo"; exit 1; }

# 1) Stop tracking runtime data (the files stay on disk). 19,000+ tracked files were Spark output.
git rm -r -q --cached data 2>/dev/null || true

# 2) .gitignore: add what is missing, without duplicating lines
add() { grep -qxF "$1" .gitignore 2>/dev/null || echo "$1" >> .gitignore; }
add ""
add "# Runtime data: generated by the pipeline, never committed"
add "data/"
add "*.crc"
add "*.bak"
add "*.pid"
add "nohup.out"
add ".pytest_cache/"

# 3) Backup copy of the generator: keep it on disk, stop tracking it
git rm -q --cached generator/generate.py.bak 2>/dev/null || true

# 4) patch_7b.py was a one-off patch that has already been applied (git history keeps it)
if [ -f patch_7b.py ]; then git rm -q patch_7b.py; fi

# 5) Makefile: `make live` still used the old 20 logins/sec and a drift point at 5,000,
#    which recreates the train/serve rate mismatch we debugged. Match the README instead.
if grep -q -- "--rate 20 --drift-after 5000" Makefile; then
  sed -i 's|# Live stream: ~20 logins/sec, drift kicks in after 5000 events|# Live stream: ~0.33 logins/sec (same pace as the training history), drift after 300 events|; s|--rate 20 --drift-after 5000|--rate 0.33 --drift-after 300|' Makefile
fi

echo
echo "Tracked files now: $(git ls-files | wc -l)  (was ~19,000+)"
echo "data/ still on disk: $(ls data 2>/dev/null | wc -l) entries"
echo
git status --short | grep -v '^D  data/' | head -20 || true
echo "(plus $(git status --short | grep -c '^D  data/') data/ files untracked)"
echo
echo "Next:  git add -A && git commit -m 'Stop tracking runtime data; remove applied patch; fix make live' && git push"
